In [3]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

In [4]:
digits = load_digits()

In [5]:
dir(digits)

['DESCR', 'data', 'images', 'target', 'target_names']

In [14]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(digits.data,digits.target,test_size=0.3)                                 

In [15]:
lr = LogisticRegression()
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

c:\python\python37\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


0.9703703703703703

In [16]:
svm = SVC()
svm.fit(X_train,y_train)
svm.score(X_test,y_test)

0.9925925925925926

In [17]:
rf = RandomForestClassifier()
rf.fit(X_train,y_train)
rf.score(X_test,y_test)

0.9777777777777777

In [19]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [20]:
for train_index , test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [22]:
def get_score(model,X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [23]:
get_score(LogisticRegression(),X_train,X_test,y_train,y_test)

c:\python\python37\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


0.9703703703703703

In [24]:
get_score(SVC(),X_train,X_test,y_train,y_test)

0.9925925925925926

In [25]:
get_score(RandomForestClassifier(),X_train,X_test,y_train,y_test)

0.9796296296296296

In [26]:
from sklearn.model_selection import StratifiedKFold

In [27]:
skfold = StratifiedKFold(n_splits=3)

In [28]:
from sklearn.model_selection import cross_val_score

In [29]:
cross_val_score(LogisticRegression(),digits.data,digits.target)

c:\python\python37\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
c:\python\python37\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  ex

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [30]:
cross_val_score(SVC(),digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [31]:
cross_val_score(RandomForestClassifier(),digits.data,digits.target)

array([0.93333333, 0.90555556, 0.95543175, 0.96657382, 0.93871866])

In [35]:
cross_val_score(RandomForestClassifier(n_estimators=10),digits.data,digits.target).mean()

0.9204425874342309

In [34]:
cross_val_score(RandomForestClassifier(n_estimators=20),digits.data,digits.target).mean()

0.9159981429897863

In [36]:
cross_val_score(RandomForestClassifier(n_estimators=30),digits.data,digits.target).mean()

0.9282389353141441

In [37]:
cross_val_score(RandomForestClassifier(n_estimators=30),digits.data,digits.target).mean()

0.9343469514082325

In [38]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data,digits.target).mean()

0.9404859176725473

In [39]:
cross_val_score(RandomForestClassifier(n_estimators=50),digits.data,digits.target).mean()

0.9382497678737233

In [40]:
cross_val_score(RandomForestClassifier(n_estimators=60),digits.data,digits.target).mean()

0.9293438563912103

In [42]:
cross_val_score(RandomForestClassifier(n_estimators=100),digits.data,digits.target).mean()

0.9393686165273911